[package]
name = "turambar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.10"
num-format = "0.4.0"
voca_rs = "1.14"
geo = "0.18"
geo-types = "0.7"